# 开发环境配置
server:
  port: 8099

spring:
  banner:
    location: banner.txt
  datasource:
    username: test
    password: 1234asdf
    url: jdbc:mysql://10.100.32.210:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 10.100.32.210
    port: 6379
    password:
    timeout: 500
    database: 0
    # password:
    lettuce:
      pool:
        min-idle: 0
        max-idle: 300
        max-active: 600
        max-wait: 300
  application:
    name: circlefk-service

mybatis-plus:
  # mapper.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  # 实体类路径 ，写了xml就不用写包名了
  type-aliases-package: com.ciicgat.circlefk.domain.entity
  configuration:
    # 驼峰
    map-underscore-to-camel-case: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-underline: false
    banner: false

logging:
  file:
    path: /home/workpace/service/log/
