server:
  port: 8087
logging:
  file:
    path: /home/workpace/bff/log/
spring:
  application:
    name: circlefk-bff

jwt:
  header: "Authorization"
  tokenPrefix: "bearer "
  secret: j*g2Ep5Ree!@X!e%yxD
  expireTime: 7205000